### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by DAYTOY-1112** [Audio-WestlakeU/FS-EEND#1]
Hello, author. I have submitted a request to obtain permission to download the pre-trained model for my research purposes. I kindly request your approval for this permission. Thank you.

**Comment by DiLiangWU** [comment]
Hello!
Thank you for your interest in our work. You can download the pre-trained model.

**Comment by DAYTOY-1112** [comment]
老师不好意思，我仍然没有下载链接中的预训练模型的谷歌云盘的权限

**Comment by DiLiangWU** [comment]
不好意思，之前的链接分享有点问题。您现在再尝试一下，应该可以下载了。
