### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by DAYTOY1112** [Audio-WestlakeU/FS-EEND#10]
老师您好，请问你们有尝试过在帧级speaker embedding上面拼上使用预训练的说话人认证模型提取出的speaker embedding的相关实验吗？我这边在尝试这种做法，但实验效果一直没有达到预期

**Comment by DiLiangWU** [comment]
您好，我目前还没有做过拼接target speaker embedding的实验。不过您可以参考下Duke Kunshan University的Ming Li老师组关于target-speaker voice activity detection的研究 (https://scholars.duke.edu/person/MingLi/publications)，他们是沿着这个技术路线做的。
