### ISSUE TITLE
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

### ISSUE THREAD

**Issue by lz-hust** [Audio-WestlakeU/FS-EEND#13]
老师您好！再次感谢您提供这样一个优质的项目！
我是一名刚刚涉足SD领域的本科生，正在尝试着在在您的项目上跑通其它数据集。
我尝试着在您的提供的simu_avg_41_50epo.ckpt预训练模型上对数据集进行微调，将spk_onl_tfm_enc_dec_nonautoreg_callhome.yaml中的train_data_dir与val_data_dir更改成我的训练集与测试集位置。
此时可以正常进行训练，但是训练完最后一轮（epoch99）时，卡在Testing DataLoader 0 10%的位置后，报错：`RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1`
完整报错信息：
![image](https://github.com/user-attachments/assets/b7fe3bd8-ae5f-4c12-af8e-63bc6858679d)
![image](https://github.com/user-attachments/assets/9b41257e-fdfb-4f2b-8422-f4e7364cbba0)
![image](https://github.com/user-attachments/assets/866fc6c8-0e65-4bcf-b845-6af4dfcaf823)
![image](https://github.com/user-attachments/assets/a248441a-9e71-4249-aa42-9c1f04e813c6)
我不清楚发生了什么，训练到最后一轮发生这种问题让我绝望，希望老师能够提供指点，多谢！

**Comment by lz-hust** [comment]
可能是因为spk_onl_tfm_enc_dec_nonautoreg_callhome.yaml中的batch size更改为2的原因，因为此前batch size=4时，显示我的显存不足，我擅自将其更改为2，现在我将验证一下这个猜想，希望我能成功...

**Comment by lz-hust** [comment]
> 可能是因为spk_onl_tfm_enc_dec_nonautoreg_callhome.yaml中的batch size更改为2的原因，因为此前batch size=4时，显示我的显存不足，我擅自将其更改为2，现在我将验证一下这个猜想，希望我能成功...

好吧，并没有成功

**Comment by DiLiangWU** [comment]
您好，这是因为在spk_onl_tfm_enc_dec_10w_callhome.yaml里统一为tr/val/test设置的batch_size=4，所以当训练结束进行test时由于你的数据集一个batch内部包含的spk数目不一致（pred按照batch内部最大spk数目进行pad，而label仍保持真实spk数目），导致report_diarization_error里接收到的label和decision在spk维度出现差异。
首先training的过程不会受到影响，你之前训练得到的100个epo的ckpt已经保存在log下的话，可以用--test_from_folder 命令直接进行推理。另外，我已在test_data_loder下将batch_size改为了1。这样就可以避免在训练脚本下出现该问题了。

**Comment by lz-hust** [comment]
> 您好，这是因为在spk_onl_tfm_enc_dec_10w_callhome.yaml里统一为tr/val/test设置的batch_size=4，所以当训练结束进行test时由于你的数据集一个batch内部包含的spk数目不一致（pred按照batch内部最大spk数目进行pad，而label仍保持真实spk数目），导致report_diarization_error里接收到的label和decision在spk维度出现差异。 首先training的过程不会受到影响，你之前训练得到的100个epo的ckpt已经保存在log下的话，可以用--test_from_folder 命令直接进行推理。另外，我已在test_dataloder下将batch_size改为了1，这样就可以避免在训练脚本下出现该问题了。

多谢老师的悉心指导！现在问题已经解决了，现将问题关闭。
