### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by lz-hust** [Audio-WestlakeU/FS-EEND#14]
老师您好！抱歉再次打扰到您！
我对本项目中README中7.Evaluation存在一些疑问：
![image](https://github.com/user-attachments/assets/1ba44509-7d8b-4d41-8de7-2b07e8f16396)
我按照您在https://github.com/Audio-WestlakeU/FS-EEND/issues/5 给的回复，将train/oln_tfm_enc_dec.py文件中test_step函数注释掉的save_dir_parnt....之后的几行取消注释并换成自己的存储路径，但是我仍然不知道怎样去生成preds，是在每次infer之后会自动保存到我设置的路径下吗？但是好像并没有作用。
很抱歉我问出如此低级的问题，但仍然希望得到您的指导！这对我有很大帮助。

**Comment by DiLiangWU** [comment]
> 是在每次infer之后会自动保存到我设置的路径下吗？

是的，按照以下infer的命令，取消save_dir_parnt以下的注释，替换成自己的路径按理就可以保存推理出的prediction。check下面的np.save()也取消注释了吗，以及你这里是不是用的train/oln_tfm_enc_dec_pit.py

>python train_diaxxx.py --configs conf/xxx_infer.yaml --gpus YOUR_DEVICE_ID --test_from_folder YOUR_CKPT_SAVE_DIR

**Comment by lz-hust** [comment]
> > 是在每次infer之后会自动保存到我设置的路径下吗？
> 
> 是的，按照以下infer的命令，取消save_dir_parnt以下的注释，替换成自己的路径按理就可以保存推理出的prediction。确认一下下面的np.save()也取消注释了吗，以及您这里是不是用的train/oln_tfm_enc_dec_pit.py
> 
> > python train_diaxxx.py --configs conf/xxx_infer.yaml --gpus YOUR_DEVICE_ID --test_from_folder YOUR_CKPT_SAVE_DIR

您的意思是train文件夹下的oln_tfm_enc_dec_spk_pit.py和oln_tfm_enc_dec.py两个脚本都要进行修改吗？我不知道我有没有理解正确，我先前仅仅只将oln_tfm_enc_dec.py进行修改，应该是这个原因？
抱歉这么晚打扰您休息，辛苦了！

**Comment by DiLiangWU** [comment]
取决于您用的是[train_dia_fintn_ch.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia_fintn_ch.py)还是[train_dia.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia.py)。前者使用pit+BCE进行finetune，需要修改[oln_tfm_enc_dec_spk_pit.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec_spk_pit.py)。后者使用按照说话人顺序permutelabel+BCE进行pre-train，需要修改[oln_tfm_enc_dec.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec.py)

**Comment by lz-hust** [comment]
> 取决于您用的是[train_dia.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia.py)还是[train_dia_fintn_ch.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia_fintn_ch.py)。前者使用按照说话人顺序permute label+BCE进行pre-train，需要修改[oln_tfm_enc_dec.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec.py)。后者使用pit+BCE进行finetune，需要修改[oln_tfm_enc_dec_spk_pit.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec_spk_pit.py)

谢谢老师的指导！但是我还有一个问题，直接infer： `python train_diaxxx.py --configs conf/xxx_infer.yaml --gpus YOUR_DEVICE_ID --test_from_folder YOUR_CKPT_SAVE_DIR` 得到的preliminary_DER和将preds完整保存下来再运行metrics.py脚本进行计算得到的计算得到的mean DER有什么区别呢？最终结果是以哪个作为参考，我在我自己数据集上finetune后的模型作这两种操作，得到的结果差距很大。
![image](https://github.com/user-attachments/assets/6acacca1-7207-4a7e-9c60-a91325f180dc)
![image](https://github.com/user-attachments/assets/fefcb32a-36a1-49be-83d2-83ad346fd5ff)

**Comment by lz-hust** [comment]
谢谢老师的指导！但是我还有一个问题，直接infer： `python train_diaxxx.py --configs conf/xxx_infer.yaml --gpus YOUR_DEVICE_ID --test_from_folder YOUR_CKPT_SAVE_DIR` 得到的preliminary_DER和将preds完整保存下来再运行metrics.py脚本进行计算得到的计算得到的mean DER有什么区别呢？最终结果是以哪个作为参考，我在我自己数据集上finetune后的ckpt作这两种操作，得到的结果差距很大，我不知道怎么回事，还是我有哪里理解错了。                                                                                           
![image](https://github.com/user-attachments/assets/982f125d-e995-4f40-8a95-eb89db134d72)
![image](https://github.com/user-attachments/assets/899deb70-08b7-4eff-baef-553276cd895b)

**Comment by lz-hust** [comment]
> > 取决于您用的是[train_dia.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia.py)还是[train_dia_fintn_ch.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train_dia_fintn_ch.py)。前者使用按照说话人顺序permute label+BCE进行pre-train，需要修改[oln_tfm_enc_dec.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec.py)。后者使用pit+BCE进行finetune，需要修改[oln_tfm_enc_dec_spk_pit.py](https://github.com/Audio-WestlakeU/FS-EEND/blob/main/train/oln_tfm_enc_dec_spk_pit.py)
> 
> 谢谢老师的指导！但是我还有一个问题，直接infer：得到的preliminary_DER和将preds完整保存下来再运行metrics.py：python` metrics.py --configs conf/xxx_infer.yaml进行计算得到的计算得到的mean DER有什么区别呢？最终结果是以哪个作为参考，我在我自己数据集上finetune后的ckpt作这两种操作，得到的结果差距很大，我不知道怎么回事，还是我有哪里理解错了。 ![image](https://private-user-images.githubusercontent.com/183906739/391846796-982f125d-e995-4f40-8a95-eb89db134d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTA5NTcsIm5iZiI6MTczMzIxMDY1NywicGF0aCI6Ii8xODM5MDY3MzkvMzkxODQ2Nzk2LTk4MmYxMjVkLWU5OTUtNGY0MC04YTk1LWViODlkYjEzNGQ3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNzI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTcyYzBkNTYyOGViZDQzYWM5MDNlYWQzYTBkN2I5ZGY1NjY4OTE5ZDRkYmM0ZDk5YTZkNjJmYzJhZjc0YTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ld6fWaCsEvbbvHWgyY7VeywvOZaSJILZb0o1_T19efU) ![image](https://private-user-images.githubusercontent.com/183906739/391846917-899deb70-08b7-4eff-baef-553276cd895b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTA5NTcsIm5iZiI6MTczMzIxMDY1NywicGF0aCI6Ii8xODM5MDY3MzkvMzkxODQ2OTE3LTg5OWRlYjcwLTA4YjctNGVmZi1iYWVmLTU1MzI3NmNkODk1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNzI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTZkZWE2MDMzYTUyZmJhMzBmYTVlZWIxYmJlNDU4MGRmZWQ1NjVjYzE3NTZkYjA4Yjk4ODQ1NDM0NTRiYjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y-t9dWi_wMHOUfCrt1Rf3bYvFfBU5QFg3evtZIshmE8)

**Comment by lz-hust** [comment]
> metrics.py得到的最终的DER是在preliminary_DER基础上使用了中值滤波和collar，正常来讲要比preliminary_DER的结果更好。差距过大的话，可能是哪里出现问题了

不知道是否是我实验步骤出现问题了，还请老师指点。
我是使用了公开数据集Alimeeting，它的音频为八通道，每个音频长约30分钟。我将八个通道做平均，转化为单通道。将其转化为kaldi格式。
我的具体实验步骤如下：
1.创建一份spk_onl_tfm_enc_dec_nonautoreg_callhome.yaml的拷贝，命名为ali_finetune.yaml，修改其中train_data_dir与val_data_dir为我训练集与测试集的位置，save_avg_path为我自己的模型保存路径model_save，dist_strategy为ddp，chunk_size为500，init_ckpt设置为simu_avg_41_50epo.ckpt，其余参数未改动。运行`python train_dia_fintn_ch.py --configs conf/ali_finetune.yaml --gpus YOUR_DEVICE_ID`开始进行100epoch的训练。
2.创建一份spk_onl_tfm_enc_dec_nonautoreg_callhome_infer.yaml的拷贝，命名为ali_infer.yaml，修改其中train_data_dir与val_data_dir为我测试集的位置，chunk_size修改为500，其余参数未改动。运行`python train_dia_fintn_ch.py --configs conf/ali_infer.yaml --gpus YOUR_DEVICE_ID --test_from_folder model_save`。
输出以下结果：
![image](https://github.com/user-attachments/assets/10f5602e-10e4-4e6f-91d2-635e8094a3e8)
3.因为我使用train_dia_fintn_ch.py进行infer，所以我将train/oln_tfm_enc_dec_spk_pit.py中test_step取消save_dir_parnt以下的注释，替换成自己的路径，保存推理出的pred。
4.运行visualize/gen_h5_output.py生成.h5文件。
5.运行metrics.py得到以下结果：
![image](https://github.com/user-attachments/assets/571914f3-7349-46d2-a1ca-540f18c624e9)
正如我之前提到，DER与preliminary_DER差距很大。
我很想知道是否是哪个环节出现了差错导致这样一个结果。再次感谢老师！

**Comment by DiLiangWU** [comment]
需要修改一下chunk_size，现在设置500即50s为一个chunk进行推理，但Alimeeting每个recording长度为15-30分钟，导致一个recording只有50s的prediction被保存下来，最终导致您的miss rate过大。如果您只想推测50s的结果，那么需要将同一个recording的每个chunk按照不同index都保存下来，而不是仅仅以recording名称保存导致保存结果覆盖；如果您想推理完整长度的recording结果，则需要设置chunk_size足以覆盖最大长度，例如100000。

**Comment by lz-hust** [comment]
> > chunk_size修改为500
> 
> 需要修改一下chunk_size，现在设置500即50s为一个chunk进行推理，一个recording只有50s的prediction被保存下来，但Alimeeting每个recording长度为15-30分钟，因此导致您的miss rate过大。如果您只想推测50s的结果，那么需要将同一个recording的每个chunk按照不同index都保存下来，而不是仅仅以recording名称保存导致先前结果被覆盖；如果您想推理完整长度的recording结果，则需要设置chunk_size足以覆盖最大长度，例如100000。

老师您好！抱歉叕打扰您！我还有两个问题想要请教您！
                                                                            
DER过大是因为我设置一个chunk为50s进行推理，一个30min左右的recording只有50s的prediction被保存下来，50s相对于30min来说太短，其他信息都丢失了，因此miss rate过大。不知道这一理解是否有误？那preliminary_DER是是怎么一回事呢？为什么它的结果看起来如此正常？是因为它仅仅是与recording对应的那50s去作评估吗？

我尝试了将infer中的chunk增加到足以覆盖测试集所有recording的大小，但它的结果很不理想，或者说当chunk设置到一个较大值的时候结果就已经不好了。我在想原因可能是原本一条recording的长度在30min左右，而我在微调训练时将chunk设置为500，chunk数量太多，容易导致同一条音频的不同chunk之间断联，也就是每个chunk里说话人数不同，导致infer结果不理想？但是将30min的音频全部输入，不划分chunk进行训练显然是不现实的，显存应该会过载。我想知道这个想法是否正确？如果正确的话是不是在短音频数据集比如aishell4上表现会不会更好呢？

**Comment by DiLiangWU** [comment]
> 那preliminary_DER是是怎么一回事呢？为什么它的结果看起来如此正常？是因为它仅仅是与recording对应的那50s去作评估吗？

第一个问题，推理时设置的50s分chunk，preliminary_DER是为load进来每一个chunk分别计算DER。而由于repo里保存prediction的代码是以recording为单位的，因此比如一条30min的recor，仅仅是最后一个50s chunk的推理结果被保存，因此依照保存下来的prediction去计算DER，其miss会很高。

> 我尝试了将infer中的chunk增加到足以覆盖测试集所有recording的大小，但它的结果很不理想。

这个结果是合理的，也是由于我们上个版本存在外推问题，实验结果在50s音频上大概推理到5min左右没问题，但是在30min非常长的音频上做外推，其结果则会变很差。我们在后续论文[LS-EEND: Long-Form Streaming End-to-End Neural Diarization with Online Attractor Extraction](https://arxiv.org/abs/2410.06670)专门解决长音频训练和推理的问题。该版本的代码和模型会在之后发布，您可以先参考下预印版论文。

>是不是在短音频数据集比如msdwild上表现会不会更好呢？

是的，目前版本模型在长音频推理上存在外推能力限制，在短音频上表现没问题

**Comment by lz-hust** [comment]
> > 那preliminary_DER是是怎么一回事呢？为什么它的结果看起来如此正常？是因为它仅仅是与recording对应的那50s去作评估吗？
> 
> 第一个问题，推理时设置的50s分chunk，preliminary_DER是为load进来每一个chunk分别计算DER然后取平均。而repo里保存prediction的代码是以recording为单位的。比如一条30min的recor，这里的preliminary_DER是30*60/50个chunk分别计算的DER，但是仅仅是最后一个50s chunk的推理结果被保存（之前的chunk结果被覆盖了），因此依照保存下来的prediction去计算DER，其miss会很高。
> 
> > 我尝试了将infer中的chunk增加到足以覆盖测试集所有recording的大小，但它的结果很不理想。
> 
> 这个结果是合理的，也是由于我们上个版本存在外推问题，实验结果在50s音频上训练大概推理到5min左右没问题，但是在30min非常长的音频上做外推，其结果则会变很差。我们在后续论文[LS-EEND: Long-Form Streaming End-to-End Neural Diarization with Online Attractor Extraction](https://arxiv.org/abs/2410.06670)专门解决长音频训练和推理的问题。该版本的代码和模型会在之后发布，您可以先参考下预印版论文。
> 
> > 是不是在短音频数据集比如msdwild上表现会不会更好呢？
> 
> 是的，目前版本模型在长音频推理上存在外推能力限制，在短音频上表现没问题

好的，谢谢老师！现将问题关闭。
