### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by DAYTOY-1112** [Audio-WestlakeU/FS-EEND#3]
老师您好，推理时运行python train_diaxxx.py文件是python train_dia.py这个代码吗

**Comment by DiLiangWU** [comment]
只针对推理部分的话使用train_dia.py和train_dia_fintn.py都可以。不过要注意使用的ckpt和数据集要相匹配。直接使用预训练模型的ckpt在新数据集(非simulated dataset或callhome)推理效果会不好，需要先fintune。
