### ISSUE TITLE
speaker_id

### ISSUE THREAD

**Issue by DAYTOY-1112** [Audio-WestlakeU/FS-EEND#6]
请问代码中的use_speaker_id应该怎么使用？是用来标志说话人的唯一性吗

**Comment by DiLiangWU** [comment]
您好，dataset是沿用https://github.com/hitachi-speech/EEND写的，use_speaker_id按我的理解是来标志说话人的唯一性的，可以用来做speaker identification等任务。但在本项speaker diarization任务中没有用到use_speaker_id。
