### ISSUE TITLE
use pre-trained model infer dataset

### ISSUE THREAD

**Issue by DTDwind** [Audio-WestlakeU/FS-EEND#7]
老师您好，我想要尝试在不经过finetune的情况下使用simu_avg_41_50epo.ckpt预训练模型评估ami的效能。
但是在这个过程中，我因为遇到了许多挫折儿感到迷茫，不知道自己是否在正确的道路上前行，希望可以得到老师的指点。
以下是我目前所尝试的过程：
首先，我准备了kaldi格式的ami测试集，并创建一份spk_onl_tfm_enc_dec_nonautoreg_infer.yaml的拷贝，命名为ami_infer.yaml，修改其中train_data_dir与val_data_dir为我测试集位置。
之后运行 `python train_dia.py --configs conf/ami_infer.yaml --gpus 0 --test_from_folder FS-EEND_simu_41_50epo_avg_model` 我遇到错误抓不到ckpt档，因此我修改 `ckpts = [x for x in all_files if (".ckpt" in x) and ("epoch" in x) and int(x.split("=")[1].split("-")[0])>=configs["log"]["start_epoch"] and int(x.split("=")[1].split("-")[0])<=configs["log"]["end_epoch"]]` 为 `ckpts = [x for x in all_files if (".ckpt" in x)]` 
但接着我遇到错误
```
Traceback (most recent call last):
  File "/mnt/HDD/HDD2/DTDwind/FS-EEND/train_dia.py", line 217, in <module>
    train(configs, gpus=setup.gpus, checkpoint_resume=setup.checkpoint_resume, test_folder=setup.test_from_folder)
  File "/mnt/HDD/HDD2/DTDwind/FS-EEND/train_dia.py", line 185, in train
    for name, param in state_dict.items():
AttributeError: 'float' object has no attribute 'items'
```
我发现程式无法正确读取ckpt当中的值，我把 `state_dict = torch.load(test_folder + "/" + c, map_location="cpu")["state_dict"]` 改成 `state_dict = torch.load(test_folder + "/" + c, map_location="cpu")` 后就能顺利读值了。

接着我遇到 `TypeError: mel() takes 0 positional arguments but 3 were given1` 我修改了 `mel_basis = librosa.filters.mel(sr=sr, n_fft=n_fft, n_mels=n_mels)` 解决。
但接着我遇到错误
```
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TransformerEncoderFusionLayer' object has no attribute 'self_attn'. Did you mean: 'self_attn1'?
```
这似乎显示ckpt存的模型跟预期的不同，但是我看其他人的issue都可以顺利的运行程式，
，我不明白为何我会遇到如此众多的问题，是不是我有哪个步骤有缺失，恳请老师指点我正确的执行方式。

**Comment by DiLiangWU** [comment]
您好，
step1和step2关于load ckpt的部分是没问题的，我们在Readme的“Performance”处做了相关说明；
step3关于mel的问题，应该属于librosa的版本问题，我们使用的librosa版本为0.9.2；
关于step4，不属于保存ckpt的名称问题：
我check了一下，保存的ckpt是没有问题的。并且可以顺利load进模型。您可以在train_dia.py中打印一下参数看看。
```
for name, param in state_dict.items():
    test_state[name] += param / len(ckpts)
    print(name, param)
```

![image](https://github.com/Audio-WestlakeU/FS-EEND/assets/88640484/be9355b0-882b-418d-8f46-44d27ffa65cd)

您可以提供一下出现该error具体的代码位置吗

**Comment by DTDwind** [comment]
老师您好，我知道原因了，您在requirements.txt中设定torch>=1.13.0，但是其实您的程式不支援更高阶的torch版本，至少我用torch==2.x不行。这是直接执行`pip install -r requirements.txt`会安装的版本。在我重新安装新的torch==1.13.0后，程式已经可以正常执行了，还请老师帮忙更新一下requirements.txt

**Comment by DiLiangWU** [comment]
好的，感谢您提供的反馈，已更新requirements.txt。

**Comment by DiLiangWU** [comment]
您好，我想请问下您在准备AMI数据集的时候，是使用 https://github.com/kaldi-asr/kaldi/tree/master/egs/ami/s5c 这个脚本吗。我在执行的时候发现在ami_download.sh中manifest 和 license的url指向不存在的文件。请问您当时遇到这个问题了吗，以及您是怎么解决的呢，谢谢！

**Comment by DTDwind** [comment]
我是直接从这里下载的https://groups.inf.ed.ac.uk/ami/download/，选择所有音档后选Headset mix，我印象中你说的脚本我执行过，但没遇到太多问题，我想两个结果应该是一致的，因为我有跑https://github.com/BUTSpeechFIT/VBx验证我音档的正确性。

**Comment by DiLiangWU** [comment]
好的，非常感谢您提供的信息

**Comment by lz-hust** [comment]
> 我是直接从这里下载的 https://groups.inf.ed.ac.uk/ami/download/ ，选择所有音档后选Headset mix，我印象中你说的脚本我执行过，但没遇到太多问题。我不确定两者结果是否一致，但我有跑 https://github.com/BUTSpeechFIT/VBx 验证我音档的正确性。 我在AHC上的结果可以跟论文上的结果对齐 DER 21.43。VBx 方法则有一点小误差。

您好！想请问您尝试AMI数据集时，是在simu_avg_41_50epo.ckpt预训练模型上进行finetune吗？我准备了kaldi格式的数据集，将spk_onl_tfm_enc_dec_nonautoreg_callhome.yaml其中的train_data_dir与val_data_dir为我的数据集的训练集和测试集的位置。但是训练完100epoch后报错：
` File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 369, in test_step
    return self.model.test_step(*args, **kwargs)
    return self.model.test_step(*args, **kwargs)
  File "/home/data/lz/FS-EEND/train/oln_tfm_enc_dec_spk_pit.py", line 224, in test_step
  File "/home/data/lz/FS-EEND/train/oln_tfm_enc_dec_spk_pit.py", line 224, in test_step
    stats = report_diarization_error(preds_realspk, labels_realspk, label_delay=self.label_delay)
  File "/home/data/lz/FS-EEND/train/utils/loss.py", line 250, in report_diarization_error
    stats = report_diarization_error(preds_realspk, labels_realspk, label_delay=self.label_delay)
  File "/home/data/lz/FS-EEND/train/utils/loss.py", line 250, in report_diarization_error
    stats = calc_diarization_error(y, t, label_delay)
  File "/home/data/lz/FS-EEND/train/utils/loss.py", line 224, in calc_diarization_error
    stats = calc_diarization_error(y, t, label_delay)
  File "/home/data/lz/FS-EEND/train/utils/loss.py", line 224, in calc_diarization_error
    n_map = ((label == 1) & (decisions == 1)).sum(axis=-1)
    n_map = ((label == 1) & (decisions == 1)).sum(axis=-1)
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1
Testing DataLoader 0:  10%|█         | 4/39 [00:05<00:44,  1.27s/it] `
请问您当时遇到过类似问题吗？
